# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 14:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Short title')),
                ('description', models.TextField(verbose_name='Description')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('neighborhood', models.CharField(max_length=50, verbose_name='Neighborhood')),
                ('state', models.CharField(choices=[('MG', 'Minas Gerais'), ('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro')], max_length=2, verbose_name='State')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Rent Value')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyPics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(blank=True, null=True, upload_to='media/properties')),
                ('url', models.URLField(blank=True, max_length=250, null=True)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
            ],
            options={
                'verbose_name': 'Property Picture',
                'verbose_name_plural': 'Property Pictures',
            },
        ),
    ]
